In [1]:
import pandas as pd
import numpy as np

In [12]:
res = pd.read_csv('state_presidential_election_results.csv')

In [13]:
res

,Unnamed: 0,year,state,state_po,state_fips,state_cen,office,dem_candidate,dem_votes,rep_candidate,totalvotes,rep_votes,total_twoparty_vote,rep_twoparty_voteshare,dem_twoparty_voteshare,dem_state_win,rep_state_win
0,0,1992,Alabama,AL,1,63,US President,"Clinton, Bill",690080,"Bush, George H.W.",1688060,804283,1494363,0.538211,0.461789,0,1
1,1,1992,Alaska,AK,2,94,US President,"Clinton, Bill",78294,"Bush, George H.W.",258506,102000,180294,0.565743,0.434257,0,1
2,2,1992,Arizona,AZ,4,86,US President,"Clinton, Bill",543050,"Bush, George H.W.",1486975,572086,1115136,0.513019,0.486981,0,1
3,3,1992,Arkansas,AR,5,71,US President,"Clinton, Bill",505823,"Bush, George H.W.",950653,337324,843147,0.400077,0.599923,1,0
4,4,1992,California,CA,6,93,US President,"Clinton, Bill",5121325,"Bush, George H.W.",11131721,3630574,8751899,0.414833,0.585167,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,352,2016,Virginia,VA,51,54,US President,"Clinton, Hillary",1981473,"Trump, Donald J.",3982752,95369,2076842,0.045920,0.954080,1,0
353,353,2016,Washington,WA,53,91,US President,"Clinton, Hillary",1742718,"Trump, Donald J.",3317019,1769443,3512161,0.503805,0.496195,0,1
354,354,2016,West Virginia,WV,54,55,US President,"Clinton, Hillary",188794,"Trump, Donald J.",713051,1221747,1410541,0.866155,0.133845,0,1
355,355,2016,Wisconsin,WI,55,35,US President,"Clinton, Hillary",1382536,"Trump, Donald J.",2976150,489371,1871907,0.261429,0.738571,1,0
356,356,2016,Wyoming,WY,56,83,US President,"Clinton, Hillary",55973,"Trump, Donald J.",258788,1405284,1461257,0.961695,0.038305,0,1

In [159]:
incomes = pd.read_csv('SQINC/SQINC1__ALL_AREAS_1948_2020.csv')

In [160]:
incomes.head(10)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1948:Q1,1948:Q2,1948:Q3,1948:Q4,1949:Q1,1949:Q2,1949:Q3,1949:Q4,1950:Q1,1950:Q2,1950:Q3,1950:Q4,1951:Q1,1951:Q2,1951:Q3,1951:Q4,1952:Q1,1952:Q2,1952:Q3,1952:Q4,1953:Q1,1953:Q2,1953:Q3,1953:Q4,1954:Q1,1954:Q2,1954:Q3,1954:Q4,1955:Q1,1955:Q2,1955:Q3,1955:Q4,1956:Q1,1956:Q2,1956:Q3,1956:Q4,1957:Q1,1957:Q2,1957:Q3,1957:Q4,1958:Q1,1958:Q2,1958:Q3,1958:Q4,1959:Q1,1959:Q2,1959:Q3,1959:Q4,1960:Q1,1960:Q2,1960:Q3,1960:Q4,1961:Q1,1961:Q2,1961:Q3,1961:Q4,1962:Q1,1962:Q2,1962:Q3,1962:Q4,1963:Q1,1963:Q2,1963:Q3,1963:Q4,1964:Q1,1964:Q2,1964:Q3,1964:Q4,1965:Q1,1965:Q2,1965:Q3,1965:Q4,1966:Q1,1966:Q2,1966:Q3,1966:Q4,1967:Q1,1967:Q2,1967:Q3,1967:Q4,1968:Q1,1968:Q2,1968:Q3,1968:Q4,1969:Q1,1969:Q2,1969:Q3,1969:Q4,1970:Q1,1970:Q2,1970:Q3,1970:Q4,1971:Q1,1971:Q2,1971:Q3,1971:Q4,1972:Q1,1972:Q2,1972:Q3,1972:Q4,1973:Q1,1973:Q2,1973:Q3,1973:Q4,1974:Q1,1974:Q2,1974:Q3,1974:Q4,1975:Q1,1975:Q2,1975:Q3,1975:Q4,1976:Q1,1976:Q2,1976:Q3,1976:Q4,1977:Q1,1977:Q2,1977:Q3,1977:Q4,1978:Q1,1978:Q2,1978:Q3,1978:Q4,1979:Q1,1979:Q2,1979:Q3,1979:Q4,1980:Q1,1980:Q2,1980:Q3,1980:Q4,1981:Q1,1981:Q2,1981:Q3,1981:Q4,1982:Q1,1982:Q2,1982:Q3,1982:Q4,1983:Q1,1983:Q2,1983:Q3,1983:Q4,1984:Q1,1984:Q2,1984:Q3,1984:Q4,1985:Q1,1985:Q2,1985:Q3,1985:Q4,1986:Q1,1986:Q2,1986:Q3,1986:Q4,1987:Q1,1987:Q2,1987:Q3,1987:Q4,1988:Q1,1988:Q2,1988:Q3,1988:Q4,1989:Q1,1989:Q2,1989:Q3,1989:Q4,1990:Q1,1990:Q2,1990:Q3,1990:Q4,1991:Q1,1991:Q2,1991:Q3,1991:Q4,1992:Q1,1992:Q2,1992:Q3,1992:Q4,1993:Q1,1993:Q2,1993:Q3,1993:Q4,1994:Q1,1994:Q2,1994:Q3,1994:Q4,1995:Q1,1995:Q2,1995:Q3,1995:Q4,1996:Q1,1996:Q2,1996:Q3,1996:Q4,1997:Q1,1997:Q2,1997:Q3,1997:Q4,1998:Q1,1998:Q2,1998:Q3,1998:Q4,1999:Q1,1999:Q2,1999:Q3,1999:Q4,2000:Q1,2000:Q2,2000:Q3,2000:Q4,2001:Q1,2001:Q2,2001:Q3,2001:Q4,2002:Q1,2002:Q2,2002:Q3,2002:Q4,2003:Q1,2003:Q2,2003:Q3,2003:Q4,2004:Q1,2004:Q2,2004:Q3,2004:Q4,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,2006:Q3,2006:Q4,2007:Q1,2007:Q2,2007:Q3,2007:Q4,2008:Q1,2008:Q2,2008:Q3,2008:Q4,2009:Q1,2009:Q2,2009:Q3,2009:Q4,2010:Q1,2010:Q2,2010:Q3,2010:Q4,2011:Q1,2011:Q2,2011:Q3,2011:Q4,2012:Q1,2012:Q2,2012:Q3,2012:Q4,2013:Q1,2013:Q2,2013:Q3,2013:Q4,2014:Q1,2014:Q2,2014:Q3,2014:Q4,2015:Q1,2015:Q2,2015:Q3,2015:Q4,2016:Q1,2016:Q2,2016:Q3,2016:Q4,2017:Q1,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3,2019:Q4,2020:Q1,2020:Q2
0,"""00000""",United States,,SQINC1,1.0,...,"Personal income (millions of dollars, seasonal...",Millions of dollars,204641.7,210069.4,215368.6,215900.3,209582.6,208642.9,208379.3,209431.3,224872.3,227018.6,235435.8,244015.9,252653.3,261187.0,265444.8,270037.8,272139.6,276136.4,283295.4,289771.8,294332.3,298155.1,297971.2,298113.0,298221.1,297872.8,299774.8,305339.5,311887.7,319078.0,325809.0,331762.6,337261.4,342935.1,348284.2,355853.6,360194.6,364875.4,369406.4,369608.5,368223.2,371359.0,378785.2,386237.8,390387.3,399652.0,402693.6,408582.2,412644.9,417480.9,419614.2,421060.1,425761.4,432032.0,438976.2,447418.4,454370.0,461904.0,466872.8,472853.2,478256.9,483117.5,490428.4,499317.2,508917.9,518360.6,527342.7,535910.8,547189.5,556840.5,570750.8,582995.2,595960.4,605817.3,617781.0,631293.3,641919.4,649043.1,662980.7,673368.8,693187.3,712776.9,730312.3,747231.5,764887.7,783275.2,801070.6,815682.5,830679.0,850468.3,865498.8,875453.9,894260.0,918564.3,933380.8,952246.9,977447.2,996338.5,1023328.8,1068517.5,1087598.0,1118065.9,1145687.5,1182520.7,1199880.3,1226440.5,1263015.8,1290311.4,1310914.8,1343040.0,1380380.3,1415684.9,1448827.8,1474514.3,1512372.3,1547101.6,1581170.6,1625727.5,1670806.8,1728823.2,1770224.2,1830326.3,1884919.2,1937926.3,1996560.0,2036213.0,2101210.8,2159044.3,2222181.9,2258681.8,2338128.5,2433647.9,2497228.1,2547719.1,2646640.9,2680071.9,2715259.6,2759786.3,2800775.1,2843355.1,2880994.1,2929827.2,2987439.9,3076442.9,3166956.4,3250328.3,3323718.0,3376949.3,3442344.7,3481190.3,3528101.6,3590247.5,3654940.9,3695495.5,3743603.1,3784548.4,3842038.3,3903140.4,3973076.0,4068117.3,4146052.1,4219797.8,4310763.2,4394638.9,4522614.8,4576966.8,4631844.6,4707241.8,4803443.9,4882851.5,4942784.0,4962204.7,4974175.0,5035724.6,5088978.5,5170285.9,5284355.6,5382969.5,5446493.9,5525861.0,5551213.2,5626720.1,5668077.9,5748916.8,5800450.9,5905601.9,5971599.5,6082859.7,6175685.8,6245217.7,6324203.9,6399464.6,6516379.8,6645191.3,6719951.2,6811221.6,6933298.5,7016296.4,7129969.0,7268176.1,7428956.3,7555774.7,7663251.0,7758393.9,7849481.7,7919943.4,8029052.8,8207774.1,8457239.7,8590487.9,8738325.2,8815247.2,8979768.9,9009243.9,8997124.9,9021218.3,9054130.3,9145507.2,9171169.1,9251845.5,9310627.7,9411677.8,9535064.7,9666233.9,9770721.0,9947476.5,10088118.6,10308807.9,10333975.8,10501549.5,10657963.3,10882295.4,11182385.3,11315347.3,11419201.8,11573421.6,11830734.9,11972482.7,12043051.1,12162547.3,12314008.5,12639164.3,12461684.3,12339250.9,11984222.0,12074284.0,12028785.5,12117936.5,12264621.9,12484065.5,12628031.1,12791261.5,13150022.1,13256612.9,13390030.5,13465246.5,13781307.7,13937514.9,13899403.0,14375306.4,13991228.0,14131115.3,14228838.5,14350830.1,14628799.0,14882520.6,15110690.0,15308850.4,15518434.8,15663418.3,15799950.4,15886756.4,15960727.8,16057870.6,16208761.0,16380164.6,16625615.0,16817988.3,17023445.1,17283279.6,17535696.2,17738973.3,17963577.7,18118772.9,18357439.3,18470545.9,18590181.8,18750880.9,18940514.5,20386810.8
1,"""00000""",United States,,SQINC1,2.0,...,"Population (midperiod, persons) 1/",Number of persons,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),308468490.0,309035333.0,309651689.0,310262435.0,310766555.0,311272558.0,311881461.0,312494324.0,313026826.0,313546115.0,314165427.0,314778212.0,315237389.0,315714561.0,316320269.0,316960658.0,317486656.0,318012149.0,318655691.0,319311414.0,319818034.0,320341493.0,320970097.0,321600164.0,322116061.0,322645774.0,323247067.0,323823160.0,324276347.0,324723790.0,325248446.0,325727634.0,326088842.0,326466512.0,326930342.0,327365581.0,327686853.0,328033835.0,328493111.0,328949848.0,329292612.0,329661076.0
2,"""00000""",United States,,SQINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),39760.0,40397.0,40781.0,41227.0,42315.0,42588.0,42933.0,43090.0,44026.0,44451.0,44242.0,45668.0,44383.0,44759.0,44982.0,45276.0,46077.0,46799.0,47420.0,47943.0,48523.0,48896.0,49226.0,49399.0,49550.0,49769.0,50144.0,50584.0,51270.0,51792.0,52340.0,53061.0,53776.0,54336.0,54946.0,55347.0,56021.0,56307.0,56592.0,57002.0,57519.0,61842.0
3,"""01000""",Alabama,5,SQINC1,1.0,...,"Personal income (millions of dollars, seasonal...",Millions of dollars,2496.0,2595.6,2669.2,2707.1,2561.9,2516.7,2473.5,2501.7,2760.8,2756.4,2830.0,2898.1,3160.5,3252.5,3332.8,3363.0,3381.6,3442.4,3532.4,3591.5,3600.6,3664.6,3667.1,3638.8,3533.4,3490.7,3500.7,3541.2,3798.9,3918.6,4056.2,4147.5,4255.3,4228.0,4259.5,4336.8,4452.3,4531.4,4586.9,4583.4,4563.8,4723.6,4757.7,4886.2,4907.8,4997.6,4979.9,5022.7,5113.2,5207.8,5208.9,5223.1,5267.8,5302.0,5370.1,5500.5,5549.9,5604.1,5638.4,5744.0,5805.6,5889.1,6052.1,6189.4,6305.8,6440.5,6554.3,6689.7,6893.7,6977.0,7117.3,7221.7,7399.0,7499.9,7608.7,7747.8,7804.7,7896.6,8052.4,8213.4,8423.1,8655.5,8857.4,9013.8,9374.1,9646.5,9881.3,10048.9,10291.4,10528.0,10756.4,10937.5,11245.1,11612.9,11868.6,12070.7,12527.4,12742.7,13049.8,13676.4,13923.3,14406.8,14836.4,15389.0,15545.9,15997.9,16524.5,16895.9,17265.8,17733.1,18414.7,18986.8,19713.2,20018.6,20479.8,21084.6,21336.6,22044.0,22674.2,23524.7,23990.2,25051.3,25902.3,26415.9,27293.1,27602.7,28448.8,29261.0,30054.2,30292.2,31284.3,32517.8,33511.7,33808.9,35154.3,35387.1,35697.0,36161.2,36660.0,37066.3,37632.6,38446.6,39376.0,40426.8,41443.9,42427.5,43433.5,44175.9,45149.7,45797.6,46361.8,47085.8,48127.4,48439.2,49100.4,49494.2,50215.1,50858.1,52029.5,53505.1,53741.8,54923.6,56318.1,57251.9,59186.6,60066.2,60636.1,61693.9,62858.6,64029.4,64720.4,65350.6,66496.3,67346.0,68197.0,69680.5,71230.4,72724.0,73811.8,74393.0,75592.1,76005.3,76269.3,77725.4,78648.9,80248.0,81524.9,82972.0,84243.7,85028.5,85945.7,86676.4,87452.5,89128.4,89967.4,90851.7,92586.7,93152.6,94379.3,95806.9,98402.8,99395.0,100422.6,101592.7,102248.2,102569.9,103832.0,105162.2,106495.3,108199.4,108590.5,110135.1,111152.5,112370.8,112338.3,112758.1,113357.3,114937.8,115665.8,116806.3,118377.4,119079.3,120702.4,122685.2,125134.6,127744.8,129787.1,132293.0,133147.8,135407.9,136796.6,139957.0,142775.3,144756.7,145895.9,147275.5,150248.4,152018.0,152837.4,154204.2,155057.1,161916.5,157016.7,155477.0,153254.1,156019.3,155440.1,155867.7,157933.1,160582.1,163381.2,164169.8,166803.6,167219.1,168544.8,169203.6,171357.6,173000.4,171345.9,175512.4,173553.3,174098.6,175331.4,174678.3,176504.1,179454.2,181869.0,184003.4,187042.8,188248.7,189748.3,189806.0,190785.4,191772.0,192487.5,194082.8,197343.1,199014.2,200457.5,203184.2,206139.7,207809.1,209457.0,211604.9,214330.6,215693.3,217250.7,218521.5,221936.4,239172.5
4,"""01000""",Alabama,5,SQINC1,2.0,...,"Population (midperiod, persons) 1/",Number of persons,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),4777047.0,4782732.0,4787889.0,4792100.0,4794721.0,4797297.0,4801715.0,4806496.0,4810198.0,4813554.0,4818341.0,4823031.0,4825417.0,4828128.0,4832143.0,4836054.0,4838255.0,4840374.0,4844060.0,4847801.0,4849294.0,4851013.0,4854426.0,4858034.0,4859909.0,4862016.0,4865623.0,4869367.0,4871243.0,4873014.0,4876890.0,4881021.0,4883316.0,4885903.0,4890367.0,4895013.0,4897846.0,4901089.0,4905888.0,4910540.0,4913570.0,4917074.0
5,"""01000""",Alabama,5,SQINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),33061.0,33575.0,34124.0,34258.0,34789.0,34857.0,35101.0,35203.0,35624.0,35940.0,35561.0,36390.0,35966.0,36059.0,36284.0,36120.0,36481.0,37074.0,37545.0,37956.0,38571.0,38806.0,39088.0,39071.0,39257.0,39443.0,39561.0,39858.0,40512.0,40840.0,41104.0,41627.0,42213.0,42532.0,42831.0,43229.0,43760.0,44009.0,44284.0,44501.0,45168.0,48641.0
6,"""02000""",Alaska *,8,SQINC1,1.0,...,"Personal income (millions of dollars, seasonal...",Millions of dollars,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),343.4,373.8,408.5,439.8,470.5,516.0,542.3,620.9,559.0,647.3,626.5,628.1,639.5,657.1,653.2,648.6,653.7,621.8,615.3,626.3,622.6,639.5,646.8,653.9,660.9,671.4,683.8,691.2,667.3,683.3,681.2,645.5,660.7,653.9,674.8,699.4,712.6,704.1,679.9,704.6,753.4,807.5,820.3,844.1,815.4,790.3,791.7,788.5,804.1,810.8,848.6,860.4,874.3,892.8,910.7,925.0,962.6,993.9,1024.8,1053.0,1060.1,1081.5,1105.1,1107.1,1117.4,1137.3,1170.4,1209.6,1222.3,1248.9,1277.8,1305.6,1326.3,1354.9,1377.5,1401.7,1491.1,1558.8,1593.2,1658.2,1759.0,1773.6,1811.1,1852.1,1891.9,1954.0,2018.2,2072.4,2077.6,2091.0,2182.4,2316.1,2400.4,2458.7,2553.3,2618.2,2650.5,2898.9,3137.4,3483.8,3777.2,4010.9,4264.3,4574.8,4603.6,4943.3,5050.0,4976.3,5319.7,5201.6,4868.1,4938.1,5206.7,5221.9,5214.2,5300.8,5406.1,5446.5,5604.5,5730.1,5960.9,6148.7,6315.3,6715.3,6733.7,6950.0,7303.2,7622.3,8084.2,8638.8,9012.1,9198.3,9331.6,9388.3,9560.2,9773.8,10004.8,10072.5,10129.5,10275.6,10851.1,10899.1,11036.9,11076.1,11153.2,11103.9,11042.5,10962.7,10636.8,10573.5,10568.2,10694.1,10814.3,10943.7,11135.0,11377.3,11565.3,12083.1,12496.6,12297.0,12486.5,12776.9,12962.3,13147.6,13205.9,13236.9,13473.1,13704.4,14078.5,14174.5,14379.9,14449.8,14883.9,14913.2,15019.9,15212.2,15347.0,15423.5,15569.6,15712.4,15856.1,15882.8,15991.1,16093.4,16167.5,16296.4,16500.9,16647.2,16892.9,17254.0,17378.5,17581.1,17949.4,17998.4,18113.9,18396.2,18402.9,18551.6,18608.3,19139.9,19691.2,19973.3,20255.8,20394.3,20772.9,21288.3,21305.4,21595.0,21873.4,22054.5,22312.8,22745.4,22725.3,23128.4,23415.3,23689.6,23857.8,24100.2,24459.0,24936.4,25213.7,25650.7,26185.6,26777.6,27236.7,27647.9,27768.7,28253.3,29318.4,29868.5,29949.1,30219.4,32026.5,33079.0,32965.7,33229.1,32306.1,32919.4,33001.8,33358.5,34492.2,35060.8,35608.4,36013.9,36831.4,37576.7,38148.9,38754.3,38870.3,39201.0,39041.1,39564.6,38590.5,38606.2,39036.5,39204.7,40396.9,40986.3,41322.8,41735.5,42417.9,42548.1,42547.4,42510.0,41703.9,41657.6,41702.2,41918.8,41979.7,42178.3,42622.1,43037.4,43698.9,44029.6,44720.4,45029.4,45567.9,45859.5,46045.1,46307.9,46592.3,49181.2
7,"""02000""",Alaska *,8,SQINC1,2.0,...,"Population (midperiod, persons) 1/",Number of persons,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),708449.0,712085.0,715024.0,717164.0,719121.0,721076.0,723239.0,725387.0,727403.0,729406.0,731391.0,733201.0,734708.0,736231.0,737003.0,736952.0,736683.0,736383.0,736549.0,737005.0,737142.0,737350.0,738065.0,739129.0,739999.0,740930.0,741316.0,740998.0,740459.0,739893.0,739209.0,738173.0,736905.0,735682.0,734767.0,733944.0,732911.0,731958.0,731203.0,730430.0,729448.0,728537.0

In [161]:
#Store National Number 2020 for later use
national2020 = incomes.query('GeoName == "United States"')
national2020 = national2020[national2020.Description == 'Per capita personal income (dollars) 2/']

In [164]:
national2020 = national2020[national2020.columns[national2020.columns.str.startswith("2020")]]
national2020 = (national2020['2020:Q1'] + national2020['2020:Q2']) / 2

In [170]:
national2020 = float(national2020) # Per capita national average for 2020

In [107]:
#get rid of star and space in Alaska and Hawaii rows
incomes.GeoName = incomes.GeoName.str.replace("\*", "", regex=True)
incomes.GeoName = incomes.GeoName.str.replace("[\s]+$", "", regex=True)

In [108]:
incomes.head(12)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1948:Q1,1948:Q2,1948:Q3,1948:Q4,1949:Q1,1949:Q2,1949:Q3,1949:Q4,1950:Q1,1950:Q2,1950:Q3,1950:Q4,1951:Q1,1951:Q2,1951:Q3,1951:Q4,1952:Q1,1952:Q2,1952:Q3,1952:Q4,1953:Q1,1953:Q2,1953:Q3,1953:Q4,1954:Q1,1954:Q2,1954:Q3,1954:Q4,1955:Q1,1955:Q2,1955:Q3,1955:Q4,1956:Q1,1956:Q2,1956:Q3,1956:Q4,1957:Q1,1957:Q2,1957:Q3,1957:Q4,1958:Q1,1958:Q2,1958:Q3,1958:Q4,1959:Q1,1959:Q2,1959:Q3,1959:Q4,1960:Q1,1960:Q2,1960:Q3,1960:Q4,1961:Q1,1961:Q2,1961:Q3,1961:Q4,1962:Q1,1962:Q2,1962:Q3,1962:Q4,1963:Q1,1963:Q2,1963:Q3,1963:Q4,1964:Q1,1964:Q2,1964:Q3,1964:Q4,1965:Q1,1965:Q2,1965:Q3,1965:Q4,1966:Q1,1966:Q2,1966:Q3,1966:Q4,1967:Q1,1967:Q2,1967:Q3,1967:Q4,1968:Q1,1968:Q2,1968:Q3,1968:Q4,1969:Q1,1969:Q2,1969:Q3,1969:Q4,1970:Q1,1970:Q2,1970:Q3,1970:Q4,1971:Q1,1971:Q2,1971:Q3,1971:Q4,1972:Q1,1972:Q2,1972:Q3,1972:Q4,1973:Q1,1973:Q2,1973:Q3,1973:Q4,1974:Q1,1974:Q2,1974:Q3,1974:Q4,1975:Q1,1975:Q2,1975:Q3,1975:Q4,1976:Q1,1976:Q2,1976:Q3,1976:Q4,1977:Q1,1977:Q2,1977:Q3,1977:Q4,1978:Q1,1978:Q2,1978:Q3,1978:Q4,1979:Q1,1979:Q2,1979:Q3,1979:Q4,1980:Q1,1980:Q2,1980:Q3,1980:Q4,1981:Q1,1981:Q2,1981:Q3,1981:Q4,1982:Q1,1982:Q2,1982:Q3,1982:Q4,1983:Q1,1983:Q2,1983:Q3,1983:Q4,1984:Q1,1984:Q2,1984:Q3,1984:Q4,1985:Q1,1985:Q2,1985:Q3,1985:Q4,1986:Q1,1986:Q2,1986:Q3,1986:Q4,1987:Q1,1987:Q2,1987:Q3,1987:Q4,1988:Q1,1988:Q2,1988:Q3,1988:Q4,1989:Q1,1989:Q2,1989:Q3,1989:Q4,1990:Q1,1990:Q2,1990:Q3,1990:Q4,1991:Q1,1991:Q2,1991:Q3,1991:Q4,1992:Q1,1992:Q2,1992:Q3,1992:Q4,1993:Q1,1993:Q2,1993:Q3,1993:Q4,1994:Q1,1994:Q2,1994:Q3,1994:Q4,1995:Q1,1995:Q2,1995:Q3,1995:Q4,1996:Q1,1996:Q2,1996:Q3,1996:Q4,1997:Q1,1997:Q2,1997:Q3,1997:Q4,1998:Q1,1998:Q2,1998:Q3,1998:Q4,1999:Q1,1999:Q2,1999:Q3,1999:Q4,2000:Q1,2000:Q2,2000:Q3,2000:Q4,2001:Q1,2001:Q2,2001:Q3,2001:Q4,2002:Q1,2002:Q2,2002:Q3,2002:Q4,2003:Q1,2003:Q2,2003:Q3,2003:Q4,2004:Q1,2004:Q2,2004:Q3,2004:Q4,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,2006:Q3,2006:Q4,2007:Q1,2007:Q2,2007:Q3,2007:Q4,2008:Q1,2008:Q2,2008:Q3,2008:Q4,2009:Q1,2009:Q2,2009:Q3,2009:Q4,2010:Q1,2010:Q2,2010:Q3,2010:Q4,2011:Q1,2011:Q2,2011:Q3,2011:Q4,2012:Q1,2012:Q2,2012:Q3,2012:Q4,2013:Q1,2013:Q2,2013:Q3,2013:Q4,2014:Q1,2014:Q2,2014:Q3,2014:Q4,2015:Q1,2015:Q2,2015:Q3,2015:Q4,2016:Q1,2016:Q2,2016:Q3,2016:Q4,2017:Q1,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3,2019:Q4,2020:Q1,2020:Q2
0,"""00000""",United States,,SQINC1,1.0,...,"Personal income (millions of dollars, seasonal...",Millions of dollars,204641.7,210069.4,215368.6,215900.3,209582.6,208642.9,208379.3,209431.3,224872.3,227018.6,235435.8,244015.9,252653.3,261187.0,265444.8,270037.8,272139.6,276136.4,283295.4,289771.8,294332.3,298155.1,297971.2,298113.0,298221.1,297872.8,299774.8,305339.5,311887.7,319078.0,325809.0,331762.6,337261.4,342935.1,348284.2,355853.6,360194.6,364875.4,369406.4,369608.5,368223.2,371359.0,378785.2,386237.8,390387.3,399652.0,402693.6,408582.2,412644.9,417480.9,419614.2,421060.1,425761.4,432032.0,438976.2,447418.4,454370.0,461904.0,466872.8,472853.2,478256.9,483117.5,490428.4,499317.2,508917.9,518360.6,527342.7,535910.8,547189.5,556840.5,570750.8,582995.2,595960.4,605817.3,617781.0,631293.3,641919.4,649043.1,662980.7,673368.8,693187.3,712776.9,730312.3,747231.5,764887.7,783275.2,801070.6,815682.5,830679.0,850468.3,865498.8,875453.9,894260.0,918564.3,933380.8,952246.9,977447.2,996338.5,1023328.8,1068517.5,1087598.0,1118065.9,1145687.5,1182520.7,1199880.3,1226440.5,1263015.8,1290311.4,1310914.8,1343040.0,1380380.3,1415684.9,1448827.8,1474514.3,1512372.3,1547101.6,1581170.6,1625727.5,1670806.8,1728823.2,1770224.2,1830326.3,1884919.2,1937926.3,1996560.0,2036213.0,2101210.8,2159044.3,2222181.9,2258681.8,2338128.5,2433647.9,2497228.1,2547719.1,2646640.9,2680071.9,2715259.6,2759786.3,2800775.1,2843355.1,2880994.1,2929827.2,2987439.9,3076442.9,3166956.4,3250328.3,3323718.0,3376949.3,3442344.7,3481190.3,3528101.6,3590247.5,3654940.9,3695495.5,3743603.1,3784548.4,3842038.3,3903140.4,3973076.0,4068117.3,4146052.1,4219797.8,4310763.2,4394638.9,4522614.8,4576966.8,4631844.6,4707241.8,4803443.9,4882851.5,4942784.0,4962204.7,4974175.0,5035724.6,5088978.5,5170285.9,5284355.6,5382969.5,5446493.9,5525861.0,5551213.2,5626720.1,5668077.9,5748916.8,5800450.9,5905601.9,5971599.5,6082859.7,6175685.8,6245217.7,6324203.9,6399464.6,6516379.8,6645191.3,6719951.2,6811221.6,6933298.5,7016296.4,7129969.0,7268176.1,7428956.3,7555774.7,7663251.0,7758393.9,7849481.7,7919943.4,8029052.8,8207774.1,8457239.7,8590487.9,8738325.2,8815247.2,8979768.9,9009243.9,8997124.9,9021218.3,9054130.3,9145507.2,9171169.1,9251845.5,9310627.7,9411677.8,9535064.7,9666233.9,9770721.0,9947476.5,10088118.6,10308807.9,10333975.8,10501549.5,10657963.3,10882295.4,11182385.3,11315347.3,11419201.8,11573421.6,11830734.9,11972482.7,12043051.1,12162547.3,12314008.5,12639164.3,12461684.3,12339250.9,11984222.0,12074284.0,12028785.5,12117936.5,12264621.9,12484065.5,12628031.1,12791261.5,13150022.1,13256612.9,13390030.5,13465246.5,13781307.7,13937514.9,13899403.0,14375306.4,13991228.0,14131115.3,14228838.5,14350830.1,14628799.0,14882520.6,15110690.0,15308850.4,15518434.8,15663418.3,15799950.4,15886756.4,15960727.8,16057870.6,16208761.0,16380164.6,16625615.0,16817988.3,17023445.1,17283279.6,17535696.2,17738973.3,17963577.7,18118772.9,18357439.3,18470545.9,18590181.8,18750880.9,18940514.5,20386810.8
1,"""00000""",United States,,SQINC1,2.0,...,"Population (midperiod, persons) 1/",Number of persons,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),308468490.0,309035333.0,309651689.0,310262435.0,310766555.0,311272558.0,311881461.0,312494324.0,313026826.0,313546115.0,314165427.0,314778212.0,315237389.0,315714561.0,316320269.0,316960658.0,317486656.0,318012149.0,318655691.0,319311414.0,319818034.0,320341493.0,320970097.0,321600164.0,322116061.0,322645774.0,323247067.0,323823160.0,324276347.0,324723790.0,325248446.0,325727634.0,326088842.0,326466512.0,326930342.0,327365581.0,327686853.0,328033835.0,328493111.0,328949848.0,329292612.0,329661076.0
2,"""00000""",United States,,SQINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),39760.0,40397.0,40781.0,41227.0,42315.0,42588.0,42933.0,43090.0,44026.0,44451.0,44242.0,45668.0,44383.0,44759.0,44982.0,45276.0,46077.0,46799.0,47420.0,47943.0,48523.0,48896.0,49226.0,49399.0,49550.0,49769.0,50144.0,50584.0,51270.0,51792.0,52340.0,53061.0,53776.0,54336.0,54946.0,55347.0,56021.0,56307.0,56592.0,57002.0,57519.0,61842.0
3,"""01000""",Alabama,5,SQINC1,1.0,...,"Personal income (millions of dollars, seasonal...",Millions of dollars,2496.0,2595.6,2669.2,2707.1,2561.9,2516.7,2473.5,2501.7,2760.8,2756.4,2830.0,2898.1,3160.5,3252.5,3332.8,3363.0,3381.6,3442.4,3532.4,3591.5,3600.6,3664.6,3667.1,3638.8,3533.4,3490.7,3500.7,3541.2,3798.9,3918.6,4056.2,4147.5,4255.3,4228.0,4259.5,4336.8,4452.3,4531.4,4586.9,4583.4,4563.8,4723.6,4757.7,4886.2,4907.8,4997.6,4979.9,5022.7,5113.2,5207.8,5208.9,5223.1,5267.8,5302.0,5370.1,5500.5,5549.9,5604.1,5638.4,5744.0,5805.6,5889.1,6052.1,6189.4,6305.8,6440.5,6554.3,6689.7,6893.7,6977.0,7117.3,7221.7,7399.0,7499.9,7608.7,7747.8,7804.7,7896.6,8052.4,8213.4,8423.1,8655.5,8857.4,9013.8,9374.1,9646.5,9881.3,10048.9,10291.4,10528.0,10756.4,10937.5,11245.1,11612.9,11868.6,12070.7,12527.4,12742.7,13049.8,13676.4,13923.3,14406.8,14836.4,15389.0,15545.9,15997.9,16524.5,16895.9,17265.8,17733.1,18414.7,18986.8,19713.2,20018.6,20479.8,21084.6,21336.6,22044.0,22674.2,23524.7,23990.2,25051.3,25902.3,26415.9,27293.1,27602.7,28448.8,29261.0,30054.2,30292.2,31284.3,32517.8,33511.7,33808.9,35154.3,35387.1,35697.0,36161.2,36660.0,37066.3,37632.6,38446.6,39376.0,40426.8,41443.9,42427.5,43433.5,44175.9,45149.7,45797.6,46361.8,47085.8,48127.4,48439.2,49100.4,49494.2,50215.1,50858.1,52029.5,53505.1,53741.8,54923.6,56318.1,57251.9,59186.6,60066.2,60636.1,61693.9,62858.6,64029.4,64720.4,65350.6,66496.3,67346.0,68197.0,69680.5,71230.4,72724.0,73811.8,74393.0,75592.1,76005.3,76269.3,77725.4,78648.9,80248.0,81524.9,82972.0,84243.7,85028.5,85945.7,86676.4,87452.5,89128.4,89967.4,90851.7,92586.7,93152.6,94379.3,95806.9,98402.8,99395.0,100422.6,101592.7,102248.2,102569.9,103832.0,105162.2,106495.3,108199.4,108590.5,110135.1,111152.5,112370.8,112338.3,112758.1,113357.3,114937.8,115665.8,116806.3,118377.4,119079.3,120702.4,122685.2,125134.6,127744.8,129787.1,132293.0,133147.8,135407.9,136796.6,139957.0,142775.3,144756.7,145895.9,147275.5,150248.4,152018.0,152837.4,154204.2,155057.1,161916.5,157016.7,155477.0,153254.1,156019.3,155440.1,155867.7,157933.1,160582.1,163381.2,164169.8,166803.6,167219.1,168544.8,169203.6,171357.6,173000.4,171345.9,175512.4,173553.3,174098.6,175331.4,174678.3,176504.1,179454.2,181869.0,184003.4,187042.8,188248.7,189748.3,189806.0,190785.4,191772.0,192487.5,194082.8,197343.1,199014.2,200457.5,203184.2,206139.7,207809.1,209457.0,211604.9,214330.6,215693.3,217250.7,218521.5,221936.4,239172.5
4,"""01000""",Alabama,5,SQINC1,2.0,...,"Population (midperiod, persons) 1/",Number of persons,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),4777047.0,4782732.0,4787889.0,4792100.0,4794721.0,4797297.0,4801715.0,4806496.0,4810198.0,4813554.0,4818341.0,4823031.0,4825417.0,4828128.0,4832143.0,4836054.0,4838255.0,4840374.0,4844060.0,4847801.0,4849294.0,4851013.0,4854426.0,4858034.0,4859909.0,4862016.0,4865623.0,4869367.0,4871243.0,4873014.0,4876890.0,4881021.0,4883316.0,4885903.0,4890367.0,4895013.0,4897846.0,4901089.0,4905888.0,4910540.0,4913570.0,4917074.0
5,"""01000""",Alabama,5,SQINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),33061.0,33575.0,34124.0,34258.0,34789.0,34857.0,35101.0,35203.0,35624.0,35940.0,35561.0,36390.0,35966.0,36059.0,36284.0,36120.0,36481.0,37074.0,37545.0,37956.0,38571.0,38806.0,39088.0,39071.0,39257.0,39443.0,39561.0,39858.0,40512.0,40840.0,41104.0,41627.0,42213.0,42532.0,42831.0,43229.0,43760.0,44009.0,44284.0,44501.0,45168.0,48641.0
6,"""02000""",Alaska,8,SQINC1,1.0,...,"Personal income (millions of dollars, seasonal...",Millions of dollars,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),343.4,373.8,408.5,439.8,470.5,516.0,542.3,620.9,559.0,647.3,626.5,628.1,639.5,657.1,653.2,648.6,653.7,621.8,615.3,626.3,622.6,639.5,646.8,653.9,660.9,671.4,683.8,691.2,667.3,683.3,681.2,645.5,660.7,653.9,674.8,699.4,712.6,704.1,679.9,704.6,753.4,807.5,820.3,844.1,815.4,790.3,791.7,788.5,804.1,810.8,848.6,860.4,874.3,892.8,910.7,925.0,962.6,993.9,1024.8,1053.0,1060.1,1081.5,1105.1,1107.1,1117.4,1137.3,1170.4,1209.6,1222.3,1248.9,1277.8,1305.6,1326.3,1354.9,1377.5,1401.7,1491.1,1558.8,1593.2,1658.2,1759.0,1773.6,1811.1,1852.1,1891.9,1954.0,2018.2,2072.4,2077.6,2091.0,2182.4,2316.1,2400.4,2458.7,2553.3,2618.2,2650.5,2898.9,3137.4,3483.8,3777.2,4010.9,4264.3,4574.8,4603.6,4943.3,5050.0,4976.3,5319.7,5201.6,4868.1,4938.1,5206.7,5221.9,5214.2,5300.8,5406.1,5446.5,5604.5,5730.1,5960.9,6148.7,6315.3,6715.3,6733.7,6950.0,7303.2,7622.3,8084.2,8638.8,9012.1,9198.3,9331.6,9388.3,9560.2,9773.8,10004.8,10072.5,10129.5,10275.6,10851.1,10899.1,11036.9,11076.1,11153.2,11103.9,11042.5,10962.7,10636.8,10573.5,10568.2,10694.1,10814.3,10943.7,11135.0,11377.3,11565.3,12083.1,12496.6,12297.0,12486.5,12776.9,12962.3,13147.6,13205.9,13236.9,13473.1,13704.4,14078.5,14174.5,14379.9,14449.8,14883.9,14913.2,15019.9,15212.2,15347.0,15423.5,15569.6,15712.4,15856.1,15882.8,15991.1,16093.4,16167.5,16296.4,16500.9,16647.2,16892.9,17254.0,17378.5,17581.1,17949.4,17998.4,18113.9,18396.2,18402.9,18551.6,18608.3,19139.9,19691.2,19973.3,20255.8,20394.3,20772.9,21288.3,21305.4,21595.0,21873.4,22054.5,22312.8,22745.4,22725.3,23128.4,23415.3,23689.6,23857.8,24100.2,24459.0,24936.4,25213.7,25650.7,26185.6,26777.6,27236.7,27647.9,27768.7,28253.3,29318.4,29868.5,29949.1,30219.4,32026.5,33079.0,32965.7,33229.1,32306.1,32919.4,33001.8,33358.5,34492.2,35060.8,35608.4,36013.9,36831.4,37576.7,38148.9,38754.3,38870.3,39201.0,39041.1,39564.6,38590.5,38606.2,39036.5,39204.7,40396.9,40986.3,41322.8,41735.5,42417.9,42548.1,42547.4,42510.0,41703.9,41657.6,41702.2,41918.8,41979.7,42178.3,42622.1,43037.4,43698.9,44029.6,44720.4,45029.4,45567.9,45859.5,46045.1,46307.9,46592.3,49181.2
7,"""02000""",Alaska,8,SQINC1,2.0,...,"Population (midperiod, persons) 1/",Number of persons,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),708449.0,712085.0,715024.0,717164.0,719121.0,721076.0,723239.0,725387.0,727403.0,729406.0,731391.0,733201.0,734708.0,736231.0,737003.0,736952.0,736683.0,736383.0,736549.0,737005.0,737142.0,737350.0,738065.0,739129.0,739999.0,740930.0,741316.0,740998.0,740459.0,739893.0,739209.0,738173.0,736905.0,735682.0,734767.0,733944.0,732911.0,731958.0,731203.0,730430.0,729448.0,728537.0

In [109]:
states = res.state.unique().tolist()

In [110]:
incomes = incomes[incomes.GeoName.isin(states)] #Get only States

In [111]:
incomes.Description.unique()

array(['Personal income (millions of dollars, seasonally adjusted)',
       'Population (midperiod, persons) 1/',
       'Per capita personal income (dollars) 2/'], dtype=object)

In [112]:
incomes = incomes[incomes.Description == 'Per capita personal income (dollars) 2/']

In [123]:
incomes.drop(columns=['GeoFIPS', 'Region', 'TableName', 'LineCode', 'IndustryClassification', 'Unit'], inplace=True)

In [124]:
pd.set_option('display.max_columns', None)

In [125]:
len(incomes)

51

In [126]:
incomes = incomes[['GeoName', '2012:Q1', '2012:Q2', '2012:Q3', '2012:Q4', '2016:Q1', '2016:Q2', '2016:Q3', '2016:Q4']]

In [127]:
incomes_AK_HI = incomes.query('GeoName == "Alaska" | GeoName == "Hawaii"')

In [128]:
incomes_AK_HI['2012'] = (incomes_AK_HI['2012:Q1']+incomes_AK_HI['2012:Q2']+incomes_AK_HI['2012:Q3']+incomes_AK_HI['2012:Q4'])/4
incomes_AK_HI['2016'] = (incomes_AK_HI['2016:Q1']+incomes_AK_HI['2016:Q2']+incomes_AK_HI['2016:Q3']+incomes_AK_HI['2016:Q4'])/4

/opt/anaconda3/envs/Bayes/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/envs/Bayes/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [129]:
incomes_AK_HI = incomes_AK_HI[['GeoName','2012', '2016']]

In [130]:
incomes_AK_HI

   GeoName      2012      2016
8   Alaska  53630.25  56351.25
38  Hawaii  44774.25  51200.25

In [131]:
inc_yearly = pd.read_csv('personal_income_by_state.csv', skiprows=4)

In [132]:
inc_yearly = inc_yearly[inc_yearly.GeoName.isin(states)]

In [133]:
inc_yearly = inc_yearly.drop(columns='GeoFips')

In [134]:
inc_yearly.head()

,GeoName,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Alabama,17583.0,18129.0,18977.0,19892.0,20630.0,21516.0,22692.0,23352.0,24338.0,25104.0,25712.0,26693.0,28415.0,29832.0,31362.0,32598.0,33353.0,32608.0,33752.0,34995.0,35884.0,36110.0,37271.0,38650.0,39234.0,40473.0,42240.0,43880.0
3,Arizona,18309.0,18950.0,19869.0,20753.0,21737.0,22804.0,24176.0,24813.0,26235.0,26803.0,27149.0,28161.0,30012.0,32220.0,34686.0,35789.0,35563.0,33418.0,33638.0,34973.0,36132.0,36615.0,38246.0,39699.0,40697.0,42534.0,44414.0,46233.0
4,Arkansas,16438.0,16956.0,17758.0,18602.0,19458.0,20187.0,21222.0,21861.0,22762.0,23840.0,24266.0,25524.0,26924.0,28047.0,29438.0,31070.0,31940.0,31153.0,31927.0,33860.0,36239.0,36237.0,38264.0,39348.0,40155.0,41543.0,43292.0,44845.0
5,California,22678.0,23013.0,23581.0,24629.0,25912.0,27171.0,29100.0,30640.0,33364.0,34043.0,34214.0,35415.0,37369.0,39279.0,42088.0,43629.0,43890.0,42044.0,43636.0,46175.0,48813.0,49303.0,52363.0,55808.0,57801.0,60219.0,63711.0,66661.0
6,Colorado,21625.0,22639.0,23625.0,24995.0,26336.0,27675.0,29903.0,31477.0,34187.0,35023.0,34608.0,34935.0,35870.0,37841.0,40140.0,42024.0,42689.0,39982.0,40689.0,43575.0,45669.0,47311.0,50711.0,52147.0,52278.0,55374.0,58500.0,61348.0

In [135]:
years = [*range(1992, 2020)]

In [14]:
election_years = [1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]

In [137]:
years_cols = [str(i) for i in years]

In [138]:
inc = pd.melt(inc_yearly, id_vars='GeoName', value_vars=years_cols, var_name='Year', value_name='Inc_per_cap')

In [139]:
pd.set_option("display.max_rows", None)

In [140]:
year_group = inc.groupby('Year', as_index=False).Inc_per_cap.mean()

In [141]:
year_group['Year'] = year_group['Year'].astype('int')
inc['Year'] = inc['Year'].astype('int')

In [142]:
year_group = year_group[year_group.Year.isin(election_years)]

In [143]:
year_group

    Year   Inc_per_cap
0   1992  20241.612245
4   1996  23940.836735
8   2000  29516.551020
12  2004  33410.714286
16  2008  40194.469388
20  2012  44083.591837
24  2016  48644.469388

In [144]:
inc_mapper = dict(zip(year_group.Year, year_group.Inc_per_cap))

In [145]:
inc = inc[inc.Year.isin(election_years)]

In [146]:
inc['National_Avg'] = inc.Year.map(inc_mapper)

In [147]:
inc.loc[:, "Pct_Over_National_Average"] = ((inc.Inc_per_cap - inc.National_Avg) / inc.Inc_per_cap) * 100

In [148]:
inc.National_Avg = inc.National_Avg.round(2)

In [149]:
#inc = inc.set_index('GeoName')

In [150]:
Avg_92 = inc.National_Avg[0]
Avg_96 = inc.iloc[50]['National_Avg']
Avg_2000 = inc.iloc[99].National_Avg
Avg_2004 = inc.iloc[148].National_Avg 
Avg_2008 = inc.iloc[196].National_Avg
Avg_2012_AK = incomes_AK_HI.loc[8, '2012']
Avg_2012_HI = incomes_AK_HI.loc[38, '2012']
Avg_2016_AK = incomes_AK_HI.loc[8, '2016']
Avg_2016_HI = incomes_AK_HI.loc[38, '2016']

In [151]:
inc = inc.drop(columns = 'National_Avg')

In [152]:
inc.loc[1225] = ['Alaska',1992, Avg_92, 0]
inc.loc[1226] = ['Hawaii', 1992, Avg_92, 0]

In [153]:
inc.loc[1227] = ['Alaska',1996, Avg_96, 0]
inc.loc[1228] = ['Hawaii', 1996, Avg_96, 0]
inc.loc[1229] = ['Alaska',2000, Avg_2000, 0]
inc.loc[1230] = ['Hawaii', 2000, Avg_2000, 0]
inc.loc[1231] = ['Alaska',2004, Avg_2004, 0]
inc.loc[1232] = ['Hawaii', 2004, Avg_2004, 0]
inc.loc[1233] = ['Alaska',2008, Avg_2008, 0]
inc.loc[1234] = ['Hawaii', 2008, Avg_2008, 0]

In [154]:
AK_2012_Pct = ((Avg_2012_AK - year_group.loc[20, 'Inc_per_cap']) / Avg_2012_AK) * 100
HI_2012_Pct = ((Avg_2012_HI - year_group.loc[20, 'Inc_per_cap']) / Avg_2012_HI) * 100
AK_2016_Pct = ((Avg_2016_AK - year_group.loc[24, 'Inc_per_cap']) / Avg_2016_AK) * 100
HI_2016_Pct = ((Avg_2016_HI - year_group.loc[24, 'Inc_per_cap']) / Avg_2016_HI) * 100

In [155]:
inc.loc[1235] = ['Alaska', 2012, Avg_2012_AK, AK_2012_Pct]
inc.loc[1236] = ['Hawaii', 2012, Avg_2012_HI, HI_2012_Pct]
inc.loc[1237] = ['Alaska', 2016, Avg_2016_AK, AK_2016_Pct]
inc.loc[1238] = ['Hawaii', 2016, Avg_2016_HI, HI_2016_Pct]

In [156]:
inc = inc.sort_values(['Year', 'GeoName'])

In [189]:
inc = inc.drop(columns='Inc_per_cap')

#### 2020 Data

Start with full 2020 incomes dataframe

In [114]:
inc2020 = incomes[incomes.columns[incomes.columns.str.startswith("2020")]]

In [115]:
inc2020.head()

    2020:Q1  2020:Q2
5   45168.0  48641.0
8   63873.0  67507.0
11  46940.0  50403.0
14  45516.0  48691.0
17  68338.0  72764.0

In [116]:
states20map = dict(zip(incomes['2020:Q2'], incomes['GeoName']))

In [117]:
inc2020['GeoName'] = inc2020['2020:Q2'].map(states20map)

/opt/anaconda3/envs/Bayes/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [119]:
len(inc2020)

51

In [121]:
inc2020["2020"] = np.mean(inc2020, axis=1)

/opt/anaconda3/envs/Bayes/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [172]:
inc2020['Pct_Over_National_Average'] = (inc2020["2020"] - national2020) / inc2020['2020']

In [174]:
inc2020 = inc2020.drop(columns=['2020:Q1', '2020:Q2', '2020'])

In [190]:
inc2020['Year'] = 2020

In [192]:
inc_full = pd.concat([inc, inc2020])

In [194]:
len(inc_full)

408

### GDP Data

In [19]:
gdp = pd.read_csv("SAGDP/SAGDP1__ALL_AREAS_1997_2019.csv")

In [20]:
gdp = gdp[gdp.GeoName.isin(states)]

In [21]:
gdp = gdp[gdp.Description == "Current-dollar GDP (millions of current dollars)"]

In [22]:
gdp.head()

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
10,"""01000""",Alabama,5,SAGDP1,3.0,...,Current-dollar GDP (millions of current dollars),Millions of current dollars,104087.4,109404.3,115030.9,119242.4,122449.3,127792.3,133739.2,146524.7,155970.4,163853.6,169678.4,172686.8,168348.0,174753.0,181349.8,186299.0,191481.0,194211.0,200402.7,203829.8,210364.4,221735.5,230968.2
18,"""02000""",Alaska,8,SAGDP1,3.0,...,Current-dollar GDP (millions of current dollars),Millions of current dollars,25744.8,24170.4,24732.6,26778.3,28420.4,29605.3,31799.7,34970.7,39774.8,44435.3,48972.6,54752.4,49585.9,52882.5,56259.9,57670.1,56622.8,55523.4,50641.6,49363.4,51803.1,54734.1,55406.1
26,"""04000""",Arizona,6,SAGDP1,3.0,...,Current-dollar GDP (millions of current dollars),Millions of current dollars,132418.0,143392.4,155344.5,164611.6,171474.2,179413.3,192751.2,205420.8,228231.2,248230.7,262322.0,259366.7,243929.4,248210.0,257947.8,268288.8,275199.1,284430.0,297141.2,311091.0,327495.8,348297.1,366189.9
34,"""05000""",Arkansas,5,SAGDP1,3.0,...,Current-dollar GDP (millions of current dollars),Millions of current dollars,59865.6,62442.5,66816.7,68770.0,70601.4,73950.4,78218.8,84624.5,89610.0,94384.5,96948.2,98955.3,97058.9,101690.0,106085.4,108745.2,114251.5,117336.7,118761.2,120374.8,123383.1,128418.9,133180.9
42,"""06000""",California,8,SAGDP1,3.0,...,Current-dollar GDP (millions of current dollars),Millions of current dollars,1070523.6,1147841.6,1247093.0,1366561.0,1384111.2,1436430.9,1527294.0,1632216.9,1753866.2,1874737.3,1955856.0,1990678.2,1920061.8,1974614.5,2050056.8,2144497.3,2262771.2,2395162.3,2553772.2,2657797.6,2819110.7,2997732.8,3137469.0

### Index of Consumer Sentiment

In [175]:
sent = pd.read_csv('consumer_sentiment_fed.csv', index_col='DATE', parse_dates=True, na_values='.', dtype={'UMCSENT': np.float64})

In [176]:
sent.tail()

            UMCSENT
DATE
2020-04-01     71.8
2020-05-01     72.3
2020-06-01     78.1
2020-07-01     72.5
2020-08-01     74.1

In [177]:
# Collect most recent 2020 data

In [178]:
election_years = [1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]

In [179]:
sent = sent[sent.index.year.isin(election_years)]

Take the average of Aug-Oct for each year as that year's measure

In [180]:
months = [8, 9, 10]
sent = sent[sent.index.month.isin(months)]

In [181]:
sent = sent.resample('Y').mean()

In [182]:
sent = sent[sent.index.year.isin(election_years)]

In [183]:
sent.index = sent.index.strftime('%Y')

In [184]:
sent

         UMCSENT
DATE
1992   75.000000
1996   95.500000
2000  106.633333
2004   93.933333
2008   63.633333
2012   78.400000
2016   89.400000
2020   74.100000

In [185]:
sent_states = pd.DataFrame(np.repeat(sent.values, 51, axis=0))

In [187]:
len(sent_states)

408

In [196]:
sent_states.loc[:, 'Year'] = inc_full.Year.tolist()

In [197]:
sent_states = sent_states.rename(columns={0: 'Idx_Consumer_Sentiment'})

In [198]:
sent_states.head()

   Idx_Consumer_Sentiment  Year
0                    75.0  1992
1                    75.0  1992
2                    75.0  1992
3                    75.0  1992
4                    75.0  1992

### Unemployment Rate

In [2]:
unemp = pd.read_excel('ststdsadata.xlsx', skiprows=7)

In [3]:
l = ["Unnamed: " + str(i) for i in range(4, 10)]
l

['Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9']

In [4]:
unemp.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
28350,51,Virginia,2020,7,6711473,4322234,64.4,3978099,59.3,344135,8.0
28351,53,Washington,2020,7,6107234,3968159,65.0,3560137,58.3,408022,10.3
28352,54,West Virginia,2020,7,1439128,759968,52.8,684524,47.6,75444,9.9
28353,55,Wisconsin,2020,7,4657405,3022822,64.9,2811211,60.4,211611,7.0
28354,56,Wyoming,2020,7,452056,294918,65.2,273901,60.6,21017,7.1

In [5]:
unemp = unemp.drop(columns= 'Unnamed: 0')

In [6]:
unemp = unemp.drop(columns = l)

In [7]:
unemp = unemp.rename(columns={'Unnamed: 1': 'State', 'Unnamed: 2': 'Year', 'Unnamed: 3': 'Month', 'Unnamed: 10': 'Unemp_Rate'})

In [8]:
unemp = unemp.query('State != "New York city" and State != "Los Angeles county"')

In [9]:
unemp = unemp.query('Year >= 1992')

In [10]:
unemp.tail()

               State  Year  Month  Unemp_Rate
28350       Virginia  2020      7         8.0
28351     Washington  2020      7        10.3
28352  West Virginia  2020      7         9.9
28353      Wisconsin  2020      7         7.0
28354        Wyoming  2020      7         7.1

In [16]:
months = [8, 9, 10]
unemp = unemp[unemp.Month.isin(months)]

In [15]:
unemp = unemp[unemp.Year.isin(election_years)]

Average Aug-Oct numbers for that year's measure

In [17]:
unemp = unemp.query("State != 'Los Angeles County'")

In [18]:
unemp = unemp.groupby(['Year', 'State'], as_index=False)['Unemp_Rate'].mean().round(2)

### Consolidate Dataframes

In [212]:
#inc = inc.drop(columns='Inc_per_cap')
inc_full = inc_full.rename(columns={'GeoName': 'State'})

In [214]:
df = unemp.merge(inc_full, how='outer', on=['State', 'Year'], validate='one_to_one')

In [215]:
#df = df.drop(columns = 'Inc_per_cap')

In [216]:
df.head()

   Year       State  Unemp_Rate  Pct_Over_National_Average
0  1992     Alabama        7.50                 -15.120356
1  1992      Alaska        8.73                   0.000000
2  1992     Arizona        7.40                 -10.555531
3  1992    Arkansas        6.93                 -23.139143
4  1992  California        9.67                  10.743398

In [217]:
df2 = df.merge(sent_states)

In [218]:
df2 = df2.drop_duplicates()

In [220]:
df2.to_csv('economic_data.csv', index=None)